name: Build and deploy Node.js app to Azure Web App - apigh

on:
  push:
    branches:
      - main
    paths:
      - 'Back-End/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install
        working-directory: Back-End
        run: npm install

      - name: Build back-end
        working-directory: Back-End
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            back-end/node_modules/**
            back-end/dist/**
            back-end/package.json
            back-end/package-lock.json
            back-end/tsconfig.json

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "apigh"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
          sync-options: --delete
