name: Build and deploy Node.js app to Azure Web App - apigh

on:
  push:
    branches:
      - main
    paths:
      - 'Back-End/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install
        working-directory: Back-End
        run: npm install

      - name: Build back-end
        working-directory: Back-End
        run: npm run build

      - name: Remove unnecessary files from back-end
        run: rm -rf Back-End/src
        

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "apigh"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: Back-End